### ISSUE TITLE
为什么在SCRATCH 2.0不支持汉字

### ISSUE THREAD

**Issue by gitriver** [LLK/scratch-flash#802] opened 2015-06-15 04:55 UTC
请在在SCRATCH 2.0支持汉字

**Comment by MrFlash67** [comment] 2015-06-15 10:35
![screen shot 2015-06-15 at 10 34 54 pm](https://cloud.githubusercontent.com/assets/4315979/8158169/c7cb0fb4-13ae-11e5-93fc-fda0d654454a.png)
I ran it through Google translate. I support the idea, but I've got no idea if it's possible in execution.

**Comment by 2jour** [comment] 2015-06-15 12:52
Hi @MrFlash67 and @gitriver , we do have Chinese character support in Scratch2.0. Is there an area in Scratch where you noticed that we have issues? Also is this for offline or online?

Thanks :)

**Comment by ntlrsk** [comment] 2015-06-15 14:51
We do not yet have Chinese character support (or any Unicode support) in the Text tool within the image editor. It is high on our priority list, however, will take time to address: https://github.com/LLK/scratch-flash/issues/231

**Comment by kaschm** [comment] 2015-08-26 14:34
marking as duplicate of https://github.com/LLK/scratch-flash/issues/231

**Closed by kaschm** 2015-08-26 14:34 UTC
Labels: duplicate
