### ISSUE TITLE
Can not use gradlew to install.

### ISSUE THREAD

**Issue by zktz** [LLK/scratch-flash#1091] opened 2016-04-26 01:21 UTC

**Comment by zktz** [comment] 2016-04-26 01:24
Hello all,

I download file from gitHub and run gradlew.

it said :
-----------------------------------------------------------------------------------------
download-osmf-zip:
      [get] Getting: http://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download
      [get] To: /root/.gradle/gradleFx/sdks/66d0cafb7bdc0d11a929d2ad5ddac64ef8d3131f/in/OSMF_1.0.zip
      [get] http://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download permanently moved to https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download
      [get] https://sourceforge.net/projects/osmf.adobe/files/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip/download moved to http://downloads.sourceforge.net/project/osmf.adobe/OSMF%201.0%20%28final%20source%2C%20ASDocs%2C%20PDF%20guides%2C%20and%20release%20notes%29/OSMF_1.0.zip?r=&ts=1461632584&use_mirror=jaist

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'scratch-flash-master'.
> The following error occurred while executing this line:
  /root/.gradle/gradleFx/sdks/66d0cafb7bdc0d11a929d2ad5ddac64ef8d3131f/frameworks/downloads.xml:125: The following error occurred while executing this line:
  /root/.gradle/gradleFx/sdks/66d0cafb7bdc0d11a929d2ad5ddac64ef8d3131f/frameworks/downloads.xml:144: Redirection detected from https to http. Protocol switch unsafe, not allowed.

**Comment by liam4** [comment] 2016-04-26 14:55
Duplicate of #1022, #1057..

**Comment by thisandagain** [comment] 2016-04-29 13:01
Tracking in #1057

**Closed by thisandagain** 2016-04-29 13:01 UTC
