### ISSUE TITLE
[3D] JavaScript Extensions not working in offline player

### ISSUE THREAD

**Issue by khanning** [LLK/scratch-flash#557] opened 2014-12-02 21:14 UTC
If you try to open a project that contains a JavaScript extension in the offline editor (v429) the extension is not visible under "More Blocks"

It worked in the offline editor v404b, the project would open and the extension blocks were still visible under "More Blocks". After updating to v429 the Extension would not load.

To test, download my [sample project](http://scratch.mit.edu/projects/37255682/) and try to open with the offline editor. Note that the extension blocks are not visible under the "More Blocks" tab.

This was originally reported [here](http://scratch.mit.edu/discuss/topic/61492/)

**Comment by CreativeComputerLab** [comment] 2015-01-24 11:19
Hi @cpseager, @2Jour - do you have any visibility as to when a milestone will be assigned will be assigned to this fix? Thanks.

**Comment by 2jour** [comment] 2015-01-29 18:00
@CreativeComputerLab I am sorry we don't have an update right now with regards to the milestone . We currently have several issues that we need to look at. Once there is an update we will let you know.

**Comment by CreativeComputerLab** [comment] 2015-02-03 09:53
@2jour  thanks. Does the "ready" label mean that issue is fixed and that the code is ready and waiting for a milestone assignment? If I pull down the source code from the appropriate branch will I be able to test the fix in my own build? If so then I'd be happy to do this and verify the fix.

**Comment by kaschm** [comment] 2015-03-10 19:17
@CreativeComputerLab - the 'ready' label is just an indication that we are ready to pull this into development (not that we have a fix ready). We are currently unable to reproduce the issue, though, so any additional information you have would be much appreciated!

**Comment by CreativeComputerLab** [comment] 2015-04-01 12:56
Hi @kaschm - Here's how to reproduce the issue:
1. Go to http://llk.github.io/scratch-extension-docs/#reporter-blocks and create an extension with the given code for the reporter block example which implements the power function- do not modify it, just copy and paste it directly into a .js file.

2. Log into a Scratch account which has developer privileges to load experimental extensions and load the extension you created in step 1.

3. Confirm that the power function works as expected in the online version.

4. Save your project to your online account. Follow the directions for uploading the extension to the server before saving the project.

5. In the online project, navigate to "File->Download to your computer" and save the project to your local computer.

6. Open the project on your local computer with the offline editor. NOTE: I've used version 434a for both the online and offline editor in this example.

7. Observe that the project doesn't work as expected. The power block seems to be highlighted in yellow as if it is running forever, but nothing is happening.

8. NOTE: You can upload this project to a non-developer online account and it will work fine.

9. You can access the project created in this example here: http://creativecomputerlab.com/extensions/PowerExtensionExample.sb2

Regards,
Steve 
P.S. Sorry for the delay in getting to this...

**Comment by cpseager** [comment] 2015-04-01 13:12
Reporters in .js extensions are treated different between the online and offline builds:

https://github.com/LLK/scratch-flash/blob/master/src/extensions/ExtensionManager.as#L196

**Comment by CreativeComputerLab** [comment] 2015-04-01 15:22
Cool, thanks :) But what is a requester? It's not covered in the extension wiki. Is there a workaround for getting reporter blocks to work in offline mode?  I would be OK with creating a modified extension for offline use.

**Comment by CreativeComputerLab** [comment] 2015-04-01 15:31
Ok, I've found that a requester block is the same as a "reporter block that waits"  https://scratch.mit.edu/discuss/topic/38970/  - it's specified by the capital 'R'.
But the remaining question is there a workaround for implementing reporter blocks? I am streaming  real time data into Scratch using reporter blocks. How can this be done in offline mode?

**Comment by cpseager** [comment] 2015-04-01 15:44
I just overwrote the WeDo extension file 

C:\Users\YOUR_USER_NAME\AppData\Roaming\edu.media.mit.Scratch2Editor\Local Store\static\js

with the example code and it does works fine offline if you load the extension into a new offline project file (as if it was the WeDo). So I think it is probably more of a .sb2 file saving/loading issue than anything else.

**Comment by CreativeComputerLab** [comment] 2015-04-01 16:37
Yes indeed! This works. My power test extension is now available and working when I load the WeDo extension which I have overwritten. Does this shed any light on the required fix? At the minimum I would love to place my own extensions in that dir and have them show up in the extension library UI.

**Comment by cpseager** [comment] 2015-04-01 16:58
On your saved file change your .sb2 extension to .zip, open up project.json inside the zip in a text editor and manually change [r] to [rR] :-)

**Comment by CreativeComputerLab** [comment] 2015-04-01 17:34
Hmm, while this worked fine for the simple power extension example, when I overwrote the WeDoExtension.js with a more complex extension (the Wii connector), it didn't work. I loaded a fresh project and loaded the "WeDo" extension which had been overwritten and my Wii extension blocks appeared as expected. However, the reporter blocks hang when clicked instead of reporting '0' when there's nothing connected.   The Wii extension consists of the following block spec below. There's nothing much different from the simple power example, just more blocks:

		blocks: [
			// Block type, block name, function name
			//Wiimote
			['r', 'button %m.button on %m.wiimote', 'wmoteButtonPress1', 'A', 'wiimote 1'], 
			[' ', 'turn %m.state light %m.light on %m.wiimote', 'setLED', 'off', '1', 'wiimote 1'], 
			[' ', 'turn rumble %m.state on %m.wiimote', 'setRumble', 'off', 'wiimote 1'], 
			['r', 'accel %m.coordXYZ on %m.wiimote', 'getAccel', 'x', 'wiimote 1'], 
			['h', 'When button %m.button pressed on %m.wiimote', 'wmoteButtonPress', 'A', 'wiimote 1'],
			['r', '%m.wiimote battery', 'wiimoteBatteryState', 'wiimote 1'], 
			//Nunchuck
			['r', 'nunchuck button %m.nButton pressed on %m.wiimote', 'nunchuckButtonPress1', 'C', 'wiimote 1'],
			['r', 'nunchuck accel %m.coordXYZ on %m.wiimote', 'nGetAccel', 'x', 'wiimote 1'], 
			['r', 'nunchuck joystick  %m.coordXY on %m.wiimote', 'getJoy', 'x', 'wiimote 1'], 
			['h', 'When nunchuck button %m.nButton pressed on %m.wiimote', 'nunchuckButtonPress', 'C', 'wiimote 1'],
			//BalanceBoard
			['r', 'topLeft %m.board', 'getTopLeft', 'balanceBoard 1'],
			['r', 'topRight %m.board', 'getTopRight', 'balanceBoard 1'],
			['r', 'bottomLeft %m.board', 'getBottomLeft', 'balanceBoard 1'],
			['r', 'bottomRight %m.board', 'getBottomRight', 'balanceBoard 1'],
			[' ', 'turn %m.board light %m.state', 'setBbLED', 'balanceBoard 1', 'off'],
			['r', '%m.board battery', 'bBoardBatteryState', 'balanceBoard 1'], 
			//Connection			
			[' ', 'connect to wii', 'Connect'],
			[' ', 'disconnect from wii', 'Disconnect']
		],

**Comment by CreativeComputerLab** [comment] 2015-04-01 17:38
Also, I've notice that I can't connect to my devices via websockets. Is the websocket API available in the offline editor? 

I also have another extension which uses the gamepad API to connect as a joystick. Is the gamepad API available in the offline editor?

Steve.

**Comment by sclements** [comment] 2015-04-02 16:06
@CreativeComputerLab here is some information about the Javascript environment that's in the offline editor: http://help.adobe.com/en_US/as3/dev/WSb2ba3b1aad8a27b0-67c0013e126afbe6c4d-8000.html

I've used the HID api, which we bundle with the extension javascript, to access some gamepads. You may be able to use that for what you're doing.

**Comment by cwillisf** [comment] 2015-04-02 16:46
@cpseager [good find](https://github.com/LLK/scratch-flash/issues/557#issuecomment-88528216) -- thanks for pointing out the difference in `loadRawExtension` vs. `loadSavedExtension`! Those two should probably share more code than they do...

@CreativeComputerLab I recognize that using an experimental extension in the offline editor is currently difficult. We're working on a new extension development process... I may have questions for people like you and @cpseager so that we can appropriately consider your use cases.

**Comment by CreativeComputerLab** [comment] 2015-04-02 17:46
@sclements - Thanks, I can see from the list that websockets aren't supported. I'm going to try to include the websocket library in with my extension and see if I can get it working that way. Also I'll play with gamepad API and see what works. 

@cswillisf - Sure, I'd like to help out. My main use case is streaming real time data into Scratch using websockets and by emulating joysticks using the gamepad API and reading the real time data
from the xyz axis channels. In most cases, the connection between the extension and data server is local. 
Do you think it is reasonable to ask for the ability to place JS extensions into a dir and have them appear in the the extension library UI in the offline editor? This will allow people to collect their own extensions without the need for the Scratch team to curate them - which I know is a big issue you're trying to solve for the online world.

**Comment by CreativeComputerLab** [comment] 2015-04-03 09:11
@cwillisf, @sclements - I cannot get a standalone JS websocket client embedded in my extension to work. It would be a hack at best if it did work. I don't see any way to stream live data into the AIR/Webkit environment to Scratch. Do you guys have any ideas on how to support this? My idea would to build a websocket client into the AIR server and expose the API to the JS environment.

**Comment by stephen-howell** [comment] 2015-04-03 10:46
Just to add my 2 cents to @CreativeComputerLab questions: I'm getting lost in the discussion trying to figure best course of action.

I am currently almost finished and ready to release a Scratch extension for Kinect. I am supporting both the Kinect version 1 and version 2 (Xbox 360 and Xbox One). 

The extension works fine for Scratch 1.4. 

However, I hoped to add Scratch 2.0 Offline and Online support but I'm not sure the extension documents reflect the current state of play with connecting and streaming data to Scratch. There is no way to use the HID mode with Kinect as far as I know. After reading this thread and taking note of @CreativeComputerLab comments above I've given up hope of supporting Offline Air version, but I still want to release an online version if possible. 

1. Apart from this forum or annoying you fine folks by email, is there a current extension guide for coders - a 'how to properly stream data to Scratch 2.0 (Online)' guide?
2. What is the current thinking on how/if extensions will be approved/provided to end users?

**Comment by CreativeComputerLab** [comment] 2015-04-11 07:54
@cwillisf, @sclements - Is JQuery supported in the javascript environment of the offline editor? I know you've added JQuery support for extensions in the online editor, I'm asking because I'd like my extensions to work the same in both offline and online environments.

**Closed** 2019-09-03 14:56 UTC
Labels: prio-medium
