### ISSUE TITLE
Mouse entering/exiting the player causes extreme lag spike

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-flash#655] opened 2015-03-04 03:42 UTC
Chrome 41, Mac OS X 10.10.2

Demonstration:
![lagggg](https://cloud.githubusercontent.com/assets/3819625/6477866/67955820-c1f6-11e4-9384-51a35a8f86ab.gif)

**Comment by as-com** [comment] 2015-03-04 04:01
Another demo: https://gfycat.com/MixedDearAcornweevil

**Comment by 2jour** [comment] 2015-03-04 16:58
May be a duplicate of https://github.com/LLK/scratch-flash/issues/615

**Comment by as-com** [comment] 2015-03-04 19:19
#615 is about lag when clicking. This issue is about lag when moving the mouse in/out of the player frame.

**Comment by as-com** [comment] 2015-03-04 20:05
(cross posted on forum http://scratch.mit.edu/discuss/topic/95330/?page=1#post-824610)
The same lag spike happens in Firefox 36, Mac OS X 10.10.2, Flash 16 in http://scratch.mit.edu/projects/10125047/.
The same happens in Opera 27 as well.

The issue does not appear in Safari 8.0.3, but interacting with the project causes Safari to...err...explode. https://github.com/LLK/scratch-flash/issues/615#issuecomment-75976966

**Comment by 2jour** [comment] 2015-03-25 19:37
able to repro on Chrome 40 mac osx 10.10.2

**Comment by sclements** [comment] 2015-04-03 19:11
It turns out this bug is caused by the version of jQuery (1.7.2) we're using. We're going to look into upgrading soon since testing shows that jQuery 1.11.2 makes the lag go away.

**Comment by rschamp** [comment] 2015-04-06 15:56
This is closed because I merged the fix in another repo, but the fix will be deployed next week.

**Comment by as-com** [comment] 2015-04-06 16:48
As a side note, why isn't the scratchr2 repo public? I want to see the
source code for the website.

**Comment by 2jour** [comment] 2015-04-10 15:26
@sclements reopening issue still see lag

**Comment by 2jour** [comment] 2015-04-14 17:10
Fixed in https://github.com/LLK/scratchr2/pull/2366

**Closed by 2jour** 2015-04-14 17:10 UTC
Labels: prio-medium
