### ISSUE TITLE
Some parts of variable have wrong context menu

### ISSUE THREAD

**Issue by djdolphin** [LLK/scratch-flash#292] opened 2014-06-18 22:37 UTC
If you right click on some areas of a variable watcher (mostly the grey part), it will bring up the stage's context menu instead of the variable's. This is most evident on the large readout - clicking will always bring up the menu for the stage, making it impossible to switch the readout again.

**Comment by 2jour** [comment] 2015-02-19 15:53
There is already an issue logged where on linux where the context menu is further away from where the right click occurred. We are closing this issue.  Please reopen if anyone disagrees https://github.com/LLK/scratch-flash/issues/632

**Comment by nathan** [comment] 2015-02-19 16:11
Different issue—the context menu appears in the right place but acts as if you've right-clicked the Stage instead of the variable watcher.

**Comment by 2jour** [comment] 2015-02-19 16:32
@nathan are you able to reproduce? I am right clicking over Sprite1: and I am getting the correct context menu.

**Comment by 2jour** [comment] 2015-02-19 16:38
Able to reproduce :)..

OS: Windows 7
Browser : Chrome
server : scratch.mit.edu
1. Create
2. go to motion tab and check mark x and y reporter
3. right click around Sprite1: and in certain areas you will see the context menu for stage

Expected: right click reporter variables should give context menu("Normal Readout" )for reporter not "Save Picture of Stage"

**Comment by cpseager** [comment] 2015-02-19 16:48
@2jour And now drag that 'Sprite1:y position' reporter to the right (so that it is no longer at the far left hand side of stage). Now try clicking on it again in the various positions - you will see the behaviour change yet again.

**Comment by 2jour** [comment] 2015-02-19 16:55
Yes i see :) thanks @cpseager

**Comment by cpseager** [comment] 2015-02-20 14:45
My suspicion when I looked at this a few weeks back was that lines such as this:

(check right click object identification)
https://github.com/LLK/scratch-flash/blob/master/src/util/GestureHandler.as#L157

and

(display right click menu)
https://github.com/LLK/scratch-flash/blob/master/src/util/GestureHandler.as#L160

are not correcting adjusting the stage X and Y values (by dividing by app.ScaleX or app.ScaleY as appropriate).

**Comment by nathan** [comment] 2015-02-20 17:33
Given that this bug cannot be reproduced on non-Windows platforms or non-Chrome browsers, that seems unlikely.

**Comment by cpseager** [comment] 2015-02-25 01:11
I think the issue is in the js context menu hack (also probably applies to #632):

In project_base.js:

     customContextMenu:function(e){

     if(!this.ASobj.ASisEditMode())return;

     var t=$(this.ASobj).offset(),

     n=(e.screenX-(window.screenX||window.screenLeft||-5))/e.pageX,
     r=n*(e.pageX-t.left),
     i=n*(e.pageY-t.top),
     s=navigator.userAgent.indexOf("Macintosh")>-1,
     o=navigator.userAgent.indexOf("Chrome")==-1;

     this.ASobj.ASrightMouseDown(r,i,s&&o)
     },

The problem is Firefox etc. define Window.ScreenX as left edge of the content window.
Chrome defines it as the left edge of the whole Chrome browser itself.

Therefore in the Scratch code above the scaling factor 'n' is always off within Chrome.

Proof of difference: Run this demo js page in Chrome and in FireFox (on Windows)
Left click in a similar place on each page and note the different values displayed for 'ScreenX' v 'ClientX' in each case.

http://www.javascripter.net/faq/mouseclickeventcoordinates.htm

So, as the right click X and Y coordinates are offset in Chrome right from the start, the position of the menu (and type of menu) are then also often displayed incorrectly.

Shift+Left Click works already in Chrome, as it does not use the javascript hack.

However this hassle could also be eliminated by removing the very dated righthand click javascript 'hack' from the online version completely, as proper RIGHT_CLICK etc. MouseEvents have been directly supported for quite a while (since Flash 11.2) -  and so would now work within the main scratch.swf without any js hack.

**Closed** 2019-09-03 14:56 UTC
Labels: prio-low
