### ISSUE TITLE
Clone creation isn't reliable

### ISSUE THREAD

**Issue by MatMeredith** [LLK/scratch-flash#738] opened 2015-04-22 16:28 UTC
Hi,

My son has been coding a Frogger program in scratch.   It was working fine up until today, but (having not made any changes) it has started failing today.

You can see the project here: https://scratch.mit.edu/projects/56801972/

There should be a constant stream of hippos, rockets, witches etc. created.   Each time one gets to e.g. x > -100, it creates a clone of itself.  This was working fine.  As of today though, only the first clone appears and no subsequent clones get created.   

Can anyone help please?  I have a very sad 6 year old who was just starting to get excited about coding!

Thanks!

**Comment by 2jour** [comment] 2015-04-23 13:06
Hi @MatMeredith did this answer your problem?
https://scratch.mit.edu/discuss/topic/109502/

**Comment by 2jour** [comment] 2015-04-28 16:39
@MatMeredith closing issue .. if you think the issue is still outstanding then reopen issue

**Closed by 2jour** 2015-04-28 16:39 UTC
Labels: Triage
