### ISSUE TITLE
[translation] When stage clicked is not translated

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-flash#993] opened 2016-01-26 14:12 UTC
The 'When stage clicked' block doesn't appear to be translated in any language. I couldn't find it in the blocks project on pootle.
reported by translator:
https://mitscratch.freshdesk.com/helpdesk/tickets/37968

**Comment by ntlrsk** [comment] 2016-01-26 20:52
See: https://github.com/LLK/scratch-flash/pull/934
but apparently not resolved yet.

**Comment by chrisgarrity** [comment] 2016-01-26 21:48
@cwillisf - any thoughts?

**Comment by cwillisf** [comment] 2016-01-26 22:04
@mewtaylor do you know what's going on here? Like @ntlrsk said, we seem to still be in the same situation described here: https://github.com/LLK/scratch-flash/pull/934#issuecomment-145908027

Basically, the Editor code is attempting to translate the string but the locale files have disabled the translation somehow. It looks correct in the template file:
https://github.com/LLK/scratch-pootle-translations/blob/master/editor/templates/editor.pot#L1577

However, in the PO files the entry is commented out with `#~` -- I assume that's the translation system's way of indicating that the string is disabled or that there's some problem with it? There are actually quite a few strings in this state:
https://github.com/LLK/scratchr2/blob/develop/static/locale/de.po#L1870

As a temporary fix I could write a quick script to uncomment them all, but we should figure out the actual root cause and fix that...

**Comment by cpseager** [comment] 2016-01-26 22:08
#~ is the standard .po file marker for 'obsolete'.

if you want to use those message they need to be un-obsoleted.

**Comment by cwillisf** [comment] 2016-01-26 22:41
@cpseager good to know -- thank you!

I'm still not sure why these strings are being marked as obsolete, though. Maybe I'm misunderstanding the pipeline. My understanding is that `editor.pot` is strictly an input file and `de.po` (for example) is strictly an output file. If that's correct then There must be something in between -- maybe something at the Pootle level? -- that's obsoleting those strings.

If I'm wrong -- that is, if the locale files (`de.po` & family) are both input and output -- then maybe we just need to un-obsolete the relevant strings in all those files? Seems a little silly, but not too difficult.

**Comment by cpseager** [comment] 2016-01-26 22:53
We use poEdit but I guess the principle is the same - an existing obsolete entry in the .po file will never be brought back to life even if you put back in the original string (via merging in the new master editor.pot file). Once a string is obsolete in the po file it stays obsolete - unless, as you suggest, you run a script to strip out those marker characters.

**Comment by cwillisf** [comment] 2016-02-17 18:16
Fixed with LLK/scratch-pootle-translations@c5631cd
There are a few steps left to propagate the results through to the editor, but the root problem is now fixed. Thanks to @mewtaylor for helping me with the Pootle part.

**Closed by cwillisf** 2016-02-17 18:16 UTC
