### ISSUE TITLE
Costume center button disappears when language is set to German

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#712] opened 2015-04-13 14:34 UTC
The longer words on the "clear" "add" and "import" buttons appear to be pushing the "costume center" and "costume vertical flip" buttons off the right edge of the editor space.  According to the forum post I learned this from,

https://scratch.mit.edu/discuss/post/936772/

it happens on other languages as well - but I have not confirmed this.  I have confirmed that it happens in production on both the online and off-line versions of the Scratch editor,

**Comment by 2jour** [comment] 2015-04-13 14:37
@paddle2see duplicate of and it will be fixed for this release #682.. 

I am closing issue. If you disagree :) then reopen

**Closed by 2jour** 2015-04-13 14:37 UTC
