### ISSUE TITLE
[Regression] [Sensor Key Pressed] Arrow Keys not working consistently

### ISSUE THREAD

**Issue by Paddle2See** [LLK/scratch-flash#880] opened 2015-08-02 20:19 UTC
Running on Scratch.ly on version 439 using Chrome on Win 7

 Staging project 35785780

Using the Left/Right/Up/Down arrow keys should move the cat around.  It doesn't work in the editor, nor from the project page, nor in full screen mode.  Oddly enough, it does work while the Ask/Answer window is waiting for text (click on the bug to trigger the Ask/Answer).

This is a pretty big problem as arrow keys are used very widely in game projects.

**Comment by 2jour** [comment] 2015-08-02 21:54
Is this a duplicate of #876? @Paddle2See

**Comment by Paddle2See** [comment] 2015-08-02 22:01
@2jour It might well be a duplicate.  I saw that issue but it only mentioned the Space key - and it was a different block.  Not knowing the internal workings, I took the cautious approach and made a new issue.  The developers can tell us if it is the same issue.

**Comment by 2jour** [comment] 2015-08-02 22:11
Ok :)

**Comment by cwillisf** [comment] 2015-08-04 16:28
I believe this is https://github.com/LLK/scratch-flash/issues/884

**Comment by 2jour** [comment] 2015-08-04 16:46
I am not sure

https://scratch.mit.edu/projects/72261050/#editor
and staging 1000005489 behave differently @cwillisf

**Closed** 2015-08-04 18:45 UTC
Labels: prio-high
