### ISSUE TITLE
[3D] Colour-space inconsistency between original & Stage3D players for brightness effect

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-flash#570] opened 2014-12-15 13:31 UTC
Looks like original uses HSL colour-space, so the "brightness" effect is controlling "lightness" in HSL, meaning that increasing the brightness effect always heads towards white.

However, I suspect the Stage3D player is using the HSV/HSB colour-space, meaning the brightness effect is controlling "value"(/"brightness") in HSV(/HSB) colour-space, hence increasing brightness effect does not always head towards white.

See this thread: http://scratch.mit.edu/discuss/topic/73118/

For differences between HSL & HSV/HSB, refer here: http://en.wikipedia.org/wiki/HSL_and_HSV
In particular, note the picture at top-right of the wikipedia page that shows HSL vs HSV/HSB.

**Comment by jwzimmer** [comment] 2017-05-18 17:20
Closed https://github.com/LLK/scratch-flash/issues/1294 as a dupe of this issue.

**Closed as completed** 2019-09-03 14:56 UTC
Labels: prio-low
