### ISSUE TITLE
Error 1095 when opening project

### ISSUE THREAD

**Issue by Scimonster** [LLK/scratch-flash#1035] opened 2016-03-07 13:44 UTC
The issue is with this project: https://scratch.mit.edu/projects/97080157/

It loads up until 9/9 assets, but never progresses and finishes opening. When i open the console i see `err | TypeError: Error #1095`

I tried looking through this codebase but couldn't find any info on what error #1095 is.

**Comment by liam4** [comment] 2016-03-07 16:55
If it matters I can reproduce this (Firefox 47/El Capitan).

**Comment by bsb20** [comment] 2016-03-07 17:10
This is likely related to an issue with our uploading process which is occasionally causing SVG files to become corrupted.  This usually seems to take the form of missing a closing quotation mark in an SVG file.  When you then try and decode the SVG, this causes 
`exception, information=TypeError: Error #1095: XML parser failure: Unterminated attribute.` 
from flash.  There is currently an open Pull Request [here](https://github.com/LLK/scratch-flash/pull/1033) which will cause the typical error message to be displayed when this specific failure happens, it is slated for the next release.  We will continue to look in to the root cause of the SVG file corruption.

**Closed by bsb20** 2016-03-07 17:10 UTC
