### ISSUE TITLE
Which sprites/ options should be included in the block dropdowns, especially when they're moved to new contexts?

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-flash#1139] opened 2016-06-14 19:14 UTC
I noticed some confusing behaviour w.r.t. which Sprites show up in the dropdowns of a script when it is dragged to a new context (via the backpack, or via the sprite pane). I am not sure what the solution should be to making that behaviour clearer, especially given the scenarios brought up by @TheLogFather and @Airhogs777 around clones and programmatically-generated variables. However, given that the current behaviour is confusing/ inconsistent*, I think it would be worth considering if we can improve it as an enhancement. The other scenarios brought up regarding how users are actually using the values in the block dropdowns & their behaviour when they change contexts (via the backpack & other avenues) should be considered when thinking about what the behaviour should be, and the scope could be widened to include new features to support those use cases.

**Here is the confusing behaviour I noticed:**
A block with a sprite's name in it (e.g. "point towards [Sprite1]") will still have that Sprite's name in it when pulled out of the backpack for that sprite: What I mean is, if you have a block like "point towards [ ]", and you have Sprite1 and Sprite2, then when you use the block in a script for Sprite1, you would expect to see Sprite2 in the dropdown (so Sprite1 can point towards Sprite2). However, you can get the block to say "point towards [Sprite1]", which doesn't make sense, when it is in a script for Sprite1, if you use the backpack.

*I would consider this behaviour inconsistent since you can get Sprite1 as the value for a block in the script area for Sprite1 by dragging it into the backpack from Sprite2's scripting area, but you can't get Sprite1 as the value for a block in the script area for Sprite1 just by dragging that block from the block menu into the scripting area (you have to make the script in the area for Sprite2 and then use the backpack to change it's context to the script area for Sprite1).

Repro:
- Go to homepage
- Click on Create icon
- Create a second sprite >
- You can name them anything, but for the purposes of the repro I'll call them Sprite1 and Sprite2
- Drag the "point towards [ ]" block into the Script area for Sprite 2 (when Sprite 2 is active)
- Change the dropdown so the block says "point towards [Sprite1]"
- Drag the block into the backpack
- Click on Sprite1 (make Sprite1 active)
- Drag the block from the backpack into the scripting area
- Note that now you have a block saying that Sprite1 should "point towards [Sprite1]", which doesn't make sense
- If you use the block in a script, it will have no effect (which makes sense/ is better than other potential behaviour)

On production:
<img width="1046" alt="screen shot 2016-06-14 at 2 29 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/16056226/8e7e869c-3242-11e6-959a-48c4b20fa53a.png">
On pre-flight:
<img width="1167" alt="screen shot 2016-06-14 at 2 22 16 pm" src="https://cloud.githubusercontent.com/assets/1320456/16056227/8e81c5be-3242-11e6-8e18-337a644ec798.png">

**Comment by Airhogs777** [comment] 2016-06-14 21:04
Please don't change this behavior. `((var name) of [current sprite v])` is the only way to access programmatically-generated variables. I know that those aren't officially supported, but they're something that I and other advanced users use all the time. Changing this behavior would make using them more difficult.

**Comment by TheLogFather** [comment] 2016-06-14 23:21
You're forgetting about clones...

All the blocks that have a sprite's name in it will refer to the *original* sprite.

That means you would use a block like this if you want to, for example, point a clone of a sprite towards the original sprite.

**Comment by jwzimmer** [comment] 2016-06-15 13:32
@TheLogFather, @Airhogs777, thanks for your feedback, that is really helpful to hear how you guys are actually using this behaviour. It sounds like what we should do is broaden this case so that it's an enhancement or feature for making it easier to use the dropdown options of these blocks (in conjunction with the backpack) with clones and programmatically-generated variables, rather than having it only represent the scenario I described. I'll check the backlog to see if there is already a case for that, and if so I'll add a link to this case there and then close this case. If there's nothing in the backlog, I'll change the title and add explanatory text to this case and keep it open. Thanks! : )

**Comment by TheLogFather** [comment] 2016-06-15 14:08
It seems to me that these menus should simply have the current sprite included, rather than omitted.
Doing so would mean this becomes a non-issue, since it's perfectly acceptable for a sprite to have a block which apparently references itself.

Anyone who looks at such a block, and initially thinks it's a bit odd for a sprite to apparently reference itself in this way, will hopefully be willing to question why it's like that, and then learn something useful from the response.

The really considerate project creator would, of course, bother to connect a comment to the offending block to explain more clearly what's going on – we all do that here, don't we... ;)

Having said that, if your reply above is suggesting the possibility of extending these menus to somehow include the ability to 'target' (attributes of) specific clones, then I'm hardly going to stop you. (Imagine how useful such a feature would be...!)
It would require some way to reference specific clones, though, and it's not obvious to me how to do that simply and intuitively. (There have been various attempts in the suggestions forum over the years.)

**Comment by jwzimmer** [comment] 2016-06-15 14:17
@TheLogFather Yes, sorry if I wasn't clear, I am not advocating any particular solution as far as "keep current sprite in menu" or "don't keep current sprite in menu". I do think it's a bit confusing either way, so I think a good enhancement would be figuring out if there's a design that could clarify the behaviour. The other scenarios you guys brought up with clones & variables should also be considered as part of any enhancement to the behaviour around what shows up in the dropdowns and when (and what happens to that information when it goes into the backpack and is transferred to another sprite).

**Comment by jwzimmer** [comment] 2016-06-15 14:32
Potentially related areas to consider:
- Suggestion that variables be insertable into more blocks, including some with drop-downs https://github.com/LLK/scratch-flash/issues/1050
- Dragging variables out of backpack into various contexts changes their global/ local status https://github.com/LLK/scratch-flash/issues/1114

**Comment by TheLogFather** [comment] 2016-06-15 14:35
I'd say that the having the current sprite in the menu doesn't lead to any actual confusion, in terms of behaviour of the UI or of the blocks.

Other 'solutions' will likely cause 'surprising/unexpected behaviour' (UI surprises are, generally, A Bad Thing), or will require some 'hoop to jump through' to reach some potentially quite useful option which is missing (i.e. the current situation). They all lead to actual UI/behaviour/feature-availability confusion.

Having it in the menu doesn't lead to any real confusion, only to a single question: "Why? What use is it?" And anyone who actually asks that question should get a sensible and comprehensible answer.

**Comment by TheLogFather** [comment] 2016-06-15 14:41
In terms of taking it into a completely new context, though (e.g. a different project where there is no sprite with such a name, etc.), that's a somewhat different issue.

I suspect that would best be addressed by some kind of system that highlights errors, as I talk about at the end of https://github.com/LLK/scratch-flash/issues/1060.

**Comment by jwzimmer** [comment] 2016-06-15 14:49
@TheLogFather, I agree with you, taking the script into a different project without any Sprite by that name is a different (but related) issue that should probably get it's own consideration.

I do think that the current behaviour is confusing and in an ideal world would be improved (which is why I don't have it labeled as a bug, but as an enhancement or feature). Here's why: I would consider this behaviour inconsistent since you can get Sprite1 as the value for a block in the script area for Sprite1 by dragging it into the backpack from Sprite2's scripting area, but you can't get Sprite1 as the value for a block in the script area for Sprite1 just by dragging that block from the block menu into the scripting area (you have to make the script in the area for Sprite2 and then use the backpack to change it's context to the script area for Sprite1). So the same block can have a different set of value options depending on how it ends up in that script area. I don't think that's necessarily a design paradigm we would want to stick with.

**Comment by TheLogFather** [comment] 2016-06-15 14:58
Yes, exactly – the current situation does lead to some kind of confusion over the inconsistency. ("Hey, where's sprite 1 in the menu?!? It's there in the other sprite!")
Allowing selection of the current sprite in the menu removes that inconsistency, as well as having good reason for its existence, since it's actually useful, as per above.
(And the backback is an unnecessary extra in this. The usual method of selecting the current sprite is simply by dragging it from a different sprite, which works perfectly fine offline where there's no backpack.)

**Comment by jwzimmer** [comment] 2016-06-15 15:45
@TheLogFather, I agree, including the current sprite in the dropdown menus could be a good solution (although I don't love things like "point towards [current sprite]", because I don't think think that makes sense... it's understandable, it's not wholly baffling, so it could be worse, but I think it could be better, too!).
Thanks for pointing out that you can get the same behaviour without the backpack. I changed my comments to reflect that.

**Closed** 2019-09-03 14:51 UTC
Labels: enhancement, feature
