### ISSUE TITLE
Projects with large (huge) amounts of scripts crash Flash (possibly freezing the browser) on loading

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratch-flash#848] opened 2015-07-14 13:11 UTC
I suspect this has to do with the GUI trying to render the scripts, so I'm not sure whether this is a bug in Scratch or a result of my carelessness. Thoughts?

[ This fix is by no means urgent, as I can always find ways to shrink the scripts significantly, but this is still not the intended behaviour. ]

**Comment by sclements** [comment] 2015-07-15 19:43
How many scripts are we talking about? Might this be the output from compiling to Scratch?

**Comment by bobbybee** [comment] 2015-07-15 21:32
@sclements Hehe, indeed. Got me :p I'm not positive how many scripts there are, although I suspect the larger issue is related to the length of the scripts. If there's no way around this other than simply beefing up the optimizer to shorten things, it's fine, but I suspect there's still a lot of room for optimization in Scratch itself to deal with this kind of thing..

**Comment by 2jour** [comment] 2015-07-16 14:53
Do you have a sample project @bobbybee ?

**Comment by TheLogFather** [comment] 2015-07-17 08:01
Messing around inside https://scratch.mit.edu/projects/10143939/ last night reminded me that I see a problem with a very specific script in there - soon after any part of it comes into view, Flash freezes and I have to close the browser tab.

The script in question is in the "Rendering" sprite. To find it, scroll all the way down to the bottom, and then scroll right to a little beyond half way. You should come across the last part of a script which ends with four "draw to ( ) ( )" custom blocks, and a "set pen to ( ) ( )" just before.

A moment later, I find I can no longer do anything. If I view this in Flash Debugger, then that actually just quits - not even a crash log!

This is on a Mac, so it's possible it will behave differently elsewhere (would be curious to know)...

**Comment by bobbybee** [comment] 2015-07-17 12:47
@TheLogFather Fascinating. Of course, I'm on Linux with Pepper Flash, so who knows who's fault it is...

**Comment by TheLogFather** [comment] 2015-07-18 14:07
@bobbybee: have you tried looking at said script with your system? -would be very interested to know if it has the same problem...

**Comment by bobbybee** [comment] 2015-07-18 16:16
@TheLogFather I can replicate the issue. Took a bit of prodding, but yes, same here. Although it's not a complete freeze, it's just incredibly high amounts of lag that it's as good as frozen. (I'm trying to move the change pen shade block)

**Comment by TheLogFather** [comment] 2015-07-19 07:30
Oh, not sure where you are...? Which change pen shade block is that? Which custom block define script is this?
I find it gets quite laggy for several of those long scripts, but it's only that one in particular which causes the crash...

**Comment by bobbybee** [comment] 2015-07-19 22:24
@TheLogFather The block that's not connected to the script, just hanging out a bit. Point is, rendering is really really slow.

**Comment by griffpatch** [comment] 2015-07-19 22:29
That is why I try to keep scripts horizontally aligned as I find scratch
allows down when accept blocks overlap their render boxes.? Perhaps it's
linked to that observation @TheLogFather made elsewhere how scratch player
shows down when drawing overlapping lines using the pen... Could it be a
flash thing? More likely just overlapping render boxes causing far more
regions to be invalidated and redrawn though!

**Comment by bobbybee** [comment] 2015-07-19 23:12
@griffpatch That would make a lot of sense... when I reported this issue, all of the scripts were at (0,0)...

How much space does Scratch need in between scripts?

**Comment by griffpatch** [comment] 2015-07-20 07:04
Not a great deal as long as there is a vertical column of empty pixels from
top to bottom between script columns... Doing a script clean up naturally
creates this.

**Comment by TheLogFather** [comment] 2015-07-20 09:37
I stripped it down to only that script (plus the custom block defines it uses, empty).
Plenty of space between scripts, I think. Still crashes...

https://scratch.mit.edu/projects/70915942/

**Comment by griffpatch** [comment] 2015-07-20 09:54
I have a very interesting thing to add!!! You'll like this :)

So, I viewed your project on my win 7 laptop and scrolled the script  into
view... It was silky smooth with no lag. So I thought I'd check out memory
usage while scrolling the page into view in case there was a peek... So I
shrunk the player window down to half size and brought up memory tool then
repeated the look inside test. WOW! SO SLOW SOOOOO SLOW - MEGA LAG browser
killer type thing! That's weird :) - So then I start playing around with
the browser window and I discover that if the script is 'wider than the
editors client window' it lags like nothing else... but if it fits within
the screen width, then its super smooth and lo lag! You can even use the
zoom out button to make the scripts fit on the page and then it's smooth...

So I assume the issue is around how scripts are rendered when they are
clipped? Does it do some crazy recursive rendering thing accidentally when
scripts are too wide? I've not looked at how this is done.

Griffpatch

**Comment by bobbybee** [comment] 2015-07-20 12:31
@griffpatch That would likely explain my situation as well--- I have some very wide blocks.

Also, I viewed Log's project fullscreen.

**Comment by sclements** [comment] 2015-07-20 15:40
Hey @bobbybee @TheLogFather @griffpatch! I've been working on refactoring Block rendering in to make it more Flash friendly. The work is here, https://github.com/LLK/scratch-flash/tree/block_render_refactor, and it runs all of the known problematic projects well. There's a little pause as it initially draws and caches a large stack but it's MUCH better than production. Perhaps @bobbybee or @TheLogFather can test their projects on this branch? Not every block interaction works yet. I still need to finish dragging parts of stacks to other sprites, make sure that duplication is supported, and get the backpack working. It's working well enough to build a project and test an existing one though.

**Comment by bobbybee** [comment] 2015-07-20 15:46
@sclements I don't have access to flex at the moment-- could you host a compiled SWF somewhere to test? (or I can just give you a project ID)

**Comment by sclements** [comment] 2015-07-20 17:35
You can give me a project ID. I hope in the future we have a location to put the auto-built SWFs from development branches.

**Comment by bobbybee** [comment] 2015-07-20 18:15
@sclements That build is working much better--- the project loads completely, albeit a bit slowly, but that's to be expected. One change I had to make was spacing the scripts out as @griffpatch explained such that the boundaries don't touch, and indeed, this works fine. However, a new problem, similar to what @TheLogFather is experiencing, has popped up: somewhere in my project I have a really wide script, the result of a performing a bitwise AND in a single command block ( :stuck_out_tongue: ) When this part of the scripts panel is rendered, Flash crashes immediately.

All in all, having this branch merged to master would be really great, and would make this project feasible to work with once more. The overlapping scripts issue is annoying, but easily fixable, so my complaints are over, haha.

@TheLogFather Does the branch fix your project?

**Comment by sclements** [comment] 2015-07-20 18:20
What's the project id?

**Comment by bobbybee** [comment] 2015-07-20 18:22
@sclements 70962080

Scroll somewhere towards the middle of the project to see what I'm referring to.

The obvious workaround, of course, would just to put a big gap in the workspace (on my project) so I can click clean up before anything get's rendered--- of course, even that would need this branch's fixes I believe.

**Comment by TheLogFather** [comment] 2015-07-22 12:08
The block render refactor makes a *huge* difference to editing!

In terms of speed, I can now edit a number of my 3d projects that are currently rather painful to edit.
And when combined with my block-highlighting system (and jump to define block), editing really becomes more of a joy again for such projects. :)

It does suffer from a few bugs still (most immediate one for editing is when dragging a block out of a slot), but I'm looking forward to seeing those sorted out so it can be merged into master...

**Comment by sclements** [comment] 2015-07-22 14:49
Can you describe the bugs in more detail? @2jour is going to test soon but if you already know about bugs I can fix I'd love to hear about them.

**Comment by sclements** [comment] 2015-07-22 15:11
Okay, I fixed the argument dragging issue.

**Comment by sclements** [comment] 2015-07-23 14:28
I also fixed comments and blocks reverting to their old positions when dragged to another sprite or somewhere invalid.

**Comment by bobbybee** [comment] 2015-07-23 14:40
Awesome.

**Comment by TheLogFather** [comment] 2015-07-23 15:30
That helps a lot - especially the argument dragging.

One glitch I'm finding is a null reference in clearRunFeedback (presumably a top-of-stack Block with non-BlockStack parent). It gets triggered when starting/stopping many projects I load.

it appears to happen for any reasonably complex project (very simple ones are fine), but I don't know the root cause as I haven't managed to replicate it so far from a blank project, and I've not found a relatively simple project yet which shows it.

**Comment by sclements** [comment] 2015-07-23 18:37
Yup, thanks for the feedback! I fixed that exception and another similar one too.

**Comment by sclements** [comment] 2015-07-23 19:20
@TheLogFather @bobbybee this'll be merged very soon but does not address wide blocks (nested arguments). *Would either of you like to take a stab at optimizing that type of rendering?* The BlockStack class is the container for the visible stacks of blocks and would be the parent of the nested arguments (instead of them being parents of each other).

**Comment by bobbybee** [comment] 2015-07-23 23:22
@sclements I would, but I'm not familiar enough with the details of the bottleneck (and optimization on Flash in general) to be of much use here.

Furthermore, if I have to, I can split up wide arguments easily. The main way these types of blocks are generated by scratch-llvm are from bitwise operations (which use huge table lookups, all nested), so it should be pretty easy to introduce a temporary variable...

**Comment by TheLogFather** [comment] 2015-07-25 11:06
@sclements: I can take a look, but I'm not sure what you have have in mind in terms of the BlockStacks for such cases...
Do you mean that there's a Block within a BlockStack within a Block within a BlockStack, etc..., for all levels of the nesting? (-which seems excessive.) Or is there only one BlockStack at the 'top' level argument? (-which seems a bit odd to treat that in such a special way.)
I suspect I'm missing something somewhere...

**Closed** 2019-09-03 14:51 UTC
Labels: prio-medium
